version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: wheelgpt
      POSTGRES_USER: wheelgpt
      POSTGRES_PASSWORD: wheelgpt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wheelgpt" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
