// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Channel struct {
	ID                   string  `db:"id" json:"id"`
	Login                string  `db:"login" json:"login"`
	Token                string  `db:"token" json:"token"`
	DisplayName          string  `db:"display_name" json:"display_name"`
	ProfileImage         string  `db:"profile_image" json:"profile_image"`
	IsLive               int64   `db:"is_live" json:"is_live"`
	CreatedAt            string  `db:"created_at" json:"created_at"`
	GuessDelayTime       float64 `db:"guess_delay_time" json:"guess_delay_time"`
	BotActiveWhenOffline int64   `db:"bot_active_when_offline" json:"bot_active_when_offline"`
	UsagePublic          int64   `db:"usage_public" json:"usage_public"`
}

type Guess struct {
	ChannelID   string `db:"channel_id" json:"channel_id"`
	UserID      string `db:"user_id" json:"user_id"`
	DisplayName string `db:"display_name" json:"display_name"`
	Time        int64  `db:"time" json:"time"`
}

type GuesserLeaderboard struct {
	ChannelID         string `db:"channel_id" json:"channel_id"`
	UserID            string `db:"user_id" json:"user_id"`
	DisplayName       string `db:"display_name" json:"display_name"`
	Points            int64  `db:"points" json:"points"`
	PerfectGuessCount int64  `db:"perfect_guess_count" json:"perfect_guess_count"`
	UpdatedAt         string `db:"updated_at" json:"updated_at"`
}

type TrackmaniaMap struct {
	ChannelID    string        `db:"channel_id" json:"channel_id"`
	Uid          string        `db:"uid" json:"uid"`
	Name         string        `db:"name" json:"name"`
	Author       string        `db:"author" json:"author"`
	AuthorTime   int64         `db:"author_time" json:"author_time"`
	GoldTime     int64         `db:"gold_time" json:"gold_time"`
	SilverTime   int64         `db:"silver_time" json:"silver_time"`
	BronzeTime   int64         `db:"bronze_time" json:"bronze_time"`
	ChampionTime int64         `db:"champion_time" json:"champion_time"`
	TmxID        sql.NullInt64 `db:"tmx_id" json:"tmx_id"`
	WorldRecord  sql.NullInt64 `db:"world_record" json:"world_record"`
}

type TrackmaniaRoom struct {
	ChannelID       string `db:"channel_id" json:"channel_id"`
	Login           string `db:"login" json:"login"`
	Name            string `db:"name" json:"name"`
	NumberOfPlayers int64  `db:"number_of_players" json:"number_of_players"`
	MaxPlayers      int64  `db:"max_players" json:"max_players"`
}
