// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const clearChannelGameState = `-- name: ClearChannelGameState :exec
DELETE FROM guess WHERE channel_id = ?
`

func (q *Queries) ClearChannelGameState(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, clearChannelGameState, channelID)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channel WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const deleteGuessesByChannel = `-- name: DeleteGuessesByChannel :exec
DELETE FROM guess WHERE channel_id = ?
`

func (q *Queries) DeleteGuessesByChannel(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteGuessesByChannel, channelID)
	return err
}

const deleteTrackmaniaMap = `-- name: DeleteTrackmaniaMap :exec
DELETE FROM trackmania_map WHERE channel_id = ?
`

func (q *Queries) DeleteTrackmaniaMap(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackmaniaMap, channelID)
	return err
}

const deleteTrackmaniaRoom = `-- name: DeleteTrackmaniaRoom :exec
DELETE FROM trackmania_room WHERE channel_id = ?
`

func (q *Queries) DeleteTrackmaniaRoom(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackmaniaRoom, channelID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, login, token, display_name, profile_image, is_live, created_at, guess_delay_time, bot_active_when_offline, usage_public FROM channel WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Token,
		&i.DisplayName,
		&i.ProfileImage,
		&i.IsLive,
		&i.CreatedAt,
		&i.GuessDelayTime,
		&i.BotActiveWhenOffline,
		&i.UsagePublic,
	)
	return i, err
}

const getChannelByLogin = `-- name: GetChannelByLogin :one
SELECT id, login, token, display_name, profile_image, is_live, created_at, guess_delay_time, bot_active_when_offline, usage_public FROM channel WHERE login = ?
`

func (q *Queries) GetChannelByLogin(ctx context.Context, login string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByLogin, login)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Token,
		&i.DisplayName,
		&i.ProfileImage,
		&i.IsLive,
		&i.CreatedAt,
		&i.GuessDelayTime,
		&i.BotActiveWhenOffline,
		&i.UsagePublic,
	)
	return i, err
}

const getGuess = `-- name: GetGuess :one
SELECT channel_id, user_id, display_name, time FROM guess WHERE channel_id = ? AND user_id = ?
`

type GetGuessParams struct {
	ChannelID string `db:"channel_id" json:"channel_id"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) GetGuess(ctx context.Context, arg GetGuessParams) (Guess, error) {
	row := q.db.QueryRowContext(ctx, getGuess, arg.ChannelID, arg.UserID)
	var i Guess
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.DisplayName,
		&i.Time,
	)
	return i, err
}

const getGuessesByChannel = `-- name: GetGuessesByChannel :many
SELECT channel_id, user_id, display_name, time FROM guess WHERE channel_id = ?
`

func (q *Queries) GetGuessesByChannel(ctx context.Context, channelID string) ([]Guess, error) {
	rows, err := q.db.QueryContext(ctx, getGuessesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guess
	for rows.Next() {
		var i Guess
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.DisplayName,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    display_name,
    points,
    perfect_guess_count,
    ROW_NUMBER() OVER (ORDER BY points DESC) AS position
FROM guesser_leaderboard
WHERE channel_id = ?
ORDER BY points DESC
LIMIT ? OFFSET ?
`

type GetLeaderboardParams struct {
	ChannelID string `db:"channel_id" json:"channel_id"`
	Limit     int64  `db:"limit" json:"limit"`
	Offset    int64  `db:"offset" json:"offset"`
}

type GetLeaderboardRow struct {
	DisplayName       string      `db:"display_name" json:"display_name"`
	Points            int64       `db:"points" json:"points"`
	PerfectGuessCount int64       `db:"perfect_guess_count" json:"perfect_guess_count"`
	Position          interface{} `db:"position" json:"position"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboard, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.DisplayName,
			&i.Points,
			&i.PerfectGuessCount,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardByName = `-- name: GetLeaderboardByName :one
SELECT
    display_name,
    points,
    ROW_NUMBER() OVER (ORDER BY points DESC) AS position
FROM guesser_leaderboard
WHERE channel_id = ?
  AND lower(display_name) = lower(?)
`

type GetLeaderboardByNameParams struct {
	ChannelID string `db:"channel_id" json:"channel_id"`
	LOWER     string `db:"LOWER" json:"LOWER"`
}

type GetLeaderboardByNameRow struct {
	DisplayName string      `db:"display_name" json:"display_name"`
	Points      int64       `db:"points" json:"points"`
	Position    interface{} `db:"position" json:"position"`
}

func (q *Queries) GetLeaderboardByName(ctx context.Context, arg GetLeaderboardByNameParams) (GetLeaderboardByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardByName, arg.ChannelID, arg.LOWER)
	var i GetLeaderboardByNameRow
	err := row.Scan(&i.DisplayName, &i.Points, &i.Position)
	return i, err
}

const getTrackmaniaMap = `-- name: GetTrackmaniaMap :one
SELECT channel_id, uid, name, author, author_time, gold_time, silver_time, bronze_time, champion_time, tmx_id, world_record FROM trackmania_map WHERE channel_id = ?
`

func (q *Queries) GetTrackmaniaMap(ctx context.Context, channelID string) (TrackmaniaMap, error) {
	row := q.db.QueryRowContext(ctx, getTrackmaniaMap, channelID)
	var i TrackmaniaMap
	err := row.Scan(
		&i.ChannelID,
		&i.Uid,
		&i.Name,
		&i.Author,
		&i.AuthorTime,
		&i.GoldTime,
		&i.SilverTime,
		&i.BronzeTime,
		&i.ChampionTime,
		&i.TmxID,
		&i.WorldRecord,
	)
	return i, err
}

const getTrackmaniaRoom = `-- name: GetTrackmaniaRoom :one
SELECT channel_id, login, name, number_of_players, max_players FROM trackmania_room WHERE channel_id = ?
`

func (q *Queries) GetTrackmaniaRoom(ctx context.Context, channelID string) (TrackmaniaRoom, error) {
	row := q.db.QueryRowContext(ctx, getTrackmaniaRoom, channelID)
	var i TrackmaniaRoom
	err := row.Scan(
		&i.ChannelID,
		&i.Login,
		&i.Name,
		&i.NumberOfPlayers,
		&i.MaxPlayers,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, login, display_name, guess_delay_time, bot_active_when_offline, usage_public FROM channel
`

type ListChannelsRow struct {
	ID                   string  `db:"id" json:"id"`
	Login                string  `db:"login" json:"login"`
	DisplayName          string  `db:"display_name" json:"display_name"`
	GuessDelayTime       float64 `db:"guess_delay_time" json:"guess_delay_time"`
	BotActiveWhenOffline int64   `db:"bot_active_when_offline" json:"bot_active_when_offline"`
	UsagePublic          int64   `db:"usage_public" json:"usage_public"`
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.DisplayName,
			&i.GuessDelayTime,
			&i.BotActiveWhenOffline,
			&i.UsagePublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateChannelToken = `-- name: RotateChannelToken :exec
UPDATE channel SET token = ? WHERE id = ?
`

type RotateChannelTokenParams struct {
	Token string `db:"token" json:"token"`
	ID    string `db:"id" json:"id"`
}

func (q *Queries) RotateChannelToken(ctx context.Context, arg RotateChannelTokenParams) error {
	_, err := q.db.ExecContext(ctx, rotateChannelToken, arg.Token, arg.ID)
	return err
}

const setChannelLive = `-- name: SetChannelLive :exec
UPDATE channel SET is_live = ? WHERE id = ?
`

type SetChannelLiveParams struct {
	IsLive int64  `db:"is_live" json:"is_live"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetChannelLive(ctx context.Context, arg SetChannelLiveParams) error {
	_, err := q.db.ExecContext(ctx, setChannelLive, arg.IsLive, arg.ID)
	return err
}

const updateChannelDetails = `-- name: UpdateChannelDetails :exec
UPDATE channel SET display_name = ?, login = ? WHERE id = ?
`

type UpdateChannelDetailsParams struct {
	DisplayName string `db:"display_name" json:"display_name"`
	Login       string `db:"login" json:"login"`
	ID          string `db:"id" json:"id"`
}

func (q *Queries) UpdateChannelDetails(ctx context.Context, arg UpdateChannelDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelDetails, arg.DisplayName, arg.Login, arg.ID)
	return err
}

const updateChannelSettings = `-- name: UpdateChannelSettings :exec
UPDATE channel SET
    guess_delay_time        = ?,
    bot_active_when_offline = ?,
    usage_public            = ?
WHERE id = ?
`

type UpdateChannelSettingsParams struct {
	GuessDelayTime       float64 `db:"guess_delay_time" json:"guess_delay_time"`
	BotActiveWhenOffline int64   `db:"bot_active_when_offline" json:"bot_active_when_offline"`
	UsagePublic          int64   `db:"usage_public" json:"usage_public"`
	ID                   string  `db:"id" json:"id"`
}

func (q *Queries) UpdateChannelSettings(ctx context.Context, arg UpdateChannelSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelSettings,
		arg.GuessDelayTime,
		arg.BotActiveWhenOffline,
		arg.UsagePublic,
		arg.ID,
	)
	return err
}

const upsertChannel = `-- name: UpsertChannel :exec
INSERT INTO channel (id, login, token, display_name, profile_image)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    display_name  = excluded.display_name,
    profile_image = excluded.profile_image,
    login         = excluded.login
`

type UpsertChannelParams struct {
	ID           string `db:"id" json:"id"`
	Login        string `db:"login" json:"login"`
	Token        string `db:"token" json:"token"`
	DisplayName  string `db:"display_name" json:"display_name"`
	ProfileImage string `db:"profile_image" json:"profile_image"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannel,
		arg.ID,
		arg.Login,
		arg.Token,
		arg.DisplayName,
		arg.ProfileImage,
	)
	return err
}

const upsertGuess = `-- name: UpsertGuess :exec
INSERT INTO guess (channel_id, user_id, display_name, time)
VALUES (?, ?, ?, ?)
ON CONFLICT (channel_id, user_id) DO UPDATE SET
    time         = excluded.time,
    display_name = excluded.display_name
`

type UpsertGuessParams struct {
	ChannelID   string `db:"channel_id" json:"channel_id"`
	UserID      string `db:"user_id" json:"user_id"`
	DisplayName string `db:"display_name" json:"display_name"`
	Time        int64  `db:"time" json:"time"`
}

func (q *Queries) UpsertGuess(ctx context.Context, arg UpsertGuessParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuess,
		arg.ChannelID,
		arg.UserID,
		arg.DisplayName,
		arg.Time,
	)
	return err
}

const upsertLeaderboard = `-- name: UpsertLeaderboard :exec
INSERT INTO guesser_leaderboard (channel_id, user_id, display_name, points, perfect_guess_count, updated_at)
VALUES (?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT (channel_id, user_id) DO UPDATE SET
    points              = guesser_leaderboard.points + excluded.points,
    perfect_guess_count = guesser_leaderboard.perfect_guess_count + excluded.perfect_guess_count,
    display_name        = excluded.display_name,
    updated_at          = datetime('now')
`

type UpsertLeaderboardParams struct {
	ChannelID         string `db:"channel_id" json:"channel_id"`
	UserID            string `db:"user_id" json:"user_id"`
	DisplayName       string `db:"display_name" json:"display_name"`
	Points            int64  `db:"points" json:"points"`
	PerfectGuessCount int64  `db:"perfect_guess_count" json:"perfect_guess_count"`
}

func (q *Queries) UpsertLeaderboard(ctx context.Context, arg UpsertLeaderboardParams) error {
	_, err := q.db.ExecContext(ctx, upsertLeaderboard,
		arg.ChannelID,
		arg.UserID,
		arg.DisplayName,
		arg.Points,
		arg.PerfectGuessCount,
	)
	return err
}

const upsertTrackmaniaMap = `-- name: UpsertTrackmaniaMap :exec
INSERT INTO trackmania_map (channel_id, uid, name, author, author_time, gold_time, silver_time, bronze_time, champion_time, tmx_id, world_record)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (channel_id) DO UPDATE SET
    uid           = excluded.uid,
    name          = excluded.name,
    author        = excluded.author,
    author_time   = excluded.author_time,
    gold_time     = excluded.gold_time,
    silver_time   = excluded.silver_time,
    bronze_time   = excluded.bronze_time,
    champion_time = excluded.champion_time,
    tmx_id        = excluded.tmx_id,
    world_record  = excluded.world_record
`

type UpsertTrackmaniaMapParams struct {
	ChannelID    string        `db:"channel_id" json:"channel_id"`
	Uid          string        `db:"uid" json:"uid"`
	Name         string        `db:"name" json:"name"`
	Author       string        `db:"author" json:"author"`
	AuthorTime   int64         `db:"author_time" json:"author_time"`
	GoldTime     int64         `db:"gold_time" json:"gold_time"`
	SilverTime   int64         `db:"silver_time" json:"silver_time"`
	BronzeTime   int64         `db:"bronze_time" json:"bronze_time"`
	ChampionTime int64         `db:"champion_time" json:"champion_time"`
	TmxID        sql.NullInt64 `db:"tmx_id" json:"tmx_id"`
	WorldRecord  sql.NullInt64 `db:"world_record" json:"world_record"`
}

func (q *Queries) UpsertTrackmaniaMap(ctx context.Context, arg UpsertTrackmaniaMapParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackmaniaMap,
		arg.ChannelID,
		arg.Uid,
		arg.Name,
		arg.Author,
		arg.AuthorTime,
		arg.GoldTime,
		arg.SilverTime,
		arg.BronzeTime,
		arg.ChampionTime,
		arg.TmxID,
		arg.WorldRecord,
	)
	return err
}

const upsertTrackmaniaRoom = `-- name: UpsertTrackmaniaRoom :exec
INSERT INTO trackmania_room (channel_id, login, name, number_of_players, max_players)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (channel_id) DO UPDATE SET
    login             = excluded.login,
    name              = excluded.name,
    number_of_players = excluded.number_of_players,
    max_players       = excluded.max_players
`

type UpsertTrackmaniaRoomParams struct {
	ChannelID       string `db:"channel_id" json:"channel_id"`
	Login           string `db:"login" json:"login"`
	Name            string `db:"name" json:"name"`
	NumberOfPlayers int64  `db:"number_of_players" json:"number_of_players"`
	MaxPlayers      int64  `db:"max_players" json:"max_players"`
}

func (q *Queries) UpsertTrackmaniaRoom(ctx context.Context, arg UpsertTrackmaniaRoomParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackmaniaRoom,
		arg.ChannelID,
		arg.Login,
		arg.Name,
		arg.NumberOfPlayers,
		arg.MaxPlayers,
	)
	return err
}
