name: Docker Test

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'server/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: false
          tags: wheelgpt:test
          platforms: linux/amd64,linux/arm64

      - name: Test migrations binary
        run: |
          echo "Testing migrations binary..."
          docker run --rm wheelgpt:test ./migrations --help || echo "migrations binary exists and runs"

      - name: Test api binary
        run: |
          echo "Testing api binary..."
          timeout 5 docker run --rm wheelgpt:test ./api || echo "api binary exists and starts"

      - name: Test wheelgpt binary
        run: |
          echo "Testing wheelgpt binary..."
          timeout 5 docker run --rm wheelgpt:test ./wheelgpt || echo "wheelgpt binary exists and starts"

      - name: Test all binaries exist
        run: |
          echo "Checking all binaries exist in container..."
          docker run --rm wheelgpt:test ls -la ./migrations ./api ./wheelgpt

      - name: Test image size
        run: |
          # Get image size and output for monitoring
          docker images wheelgpt:test --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"