name: Server Module Tests

on:
  push:
  pull_request:
    branches:
      - '*'
    paths:
      - 'server/**'

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'server/go.mod'
      - name: Run tests
        run: go test -v ./...